Add notify
wildsurfer/postgrest-notify-example pull request #2
Opened 2017-05-16 14:01 UTC by andreychuk

2017-05-16 16:24 UTC, wildsurfer commented on README.md
> +postgres=# postgres=# SELECT pg_notify('messanger', 'Ololo!');
there is typo here. messEnger

2017-05-16 16:30 UTC, andreychuk commented on README.md
> +postgres=# postgres=# SELECT pg_notify('messanger', 'Ololo!');
fixed

2017-07-20 15:20 UTC, wildsurfer requested changes

2017-07-20 15:20 UTC, wildsurfer commented on README.md
> +npm install
Is it possible to do this in Dockerfile?

2017-07-20 15:20 UTC, wildsurfer commented on .gitignore
> +consumer/src/vendor/*
Do we really need `.idea` folder for this example? Let's remove it to keep it simple

2017-07-20 15:20 UTC, wildsurfer commented on docker-compose.yml
> +      - "5432:5432"
It is not secure to open port 5432 to the world

2017-07-20 15:20 UTC, wildsurfer commented on docker-compose.yml
>      restart: always
Let's remove `restart: always` cause it isn't essential for this example

2017-07-20 15:20 UTC, wildsurfer commented on docker-compose.yml
> +    restart: always
Let's remove `restart: always` cause it isn't essential for this example

2017-07-20 15:20 UTC, wildsurfer commented on notify/Dockerfile
> +RUN chmod +x /root/run.sh
Doing `chmod` inside of Dockerfile looks wired. Instead I recommend to chmod files in git repository

2017-07-20 15:20 UTC, wildsurfer commented on notify/src/default.conf
> +server {
Do we need nginx config here?!

2017-07-20 15:20 UTC, wildsurfer commented on notify/src/wait/wait-postgres.sh
> +#!/bin/sh
Do we use this script at all?

2017-07-20 15:20 UTC, wildsurfer commented on notify/src/supervisor/README.md
> +https://www.digitalocean.com/community/tutorials/how-to-install-and-manage-supervisor-on-ubuntu-and-debian-vps
Do we need this README?

2017-07-20 15:20 UTC, wildsurfer commented on notify/src/wait/wfi/LICENSE
> +The MIT License (MIT)
`wait/wfi` seems to be some package. is it possible to add it as a package? Storing it here looks wired

2017-07-28 15:21 UTC, andreychuk commented on README.md
> +npm install
done

2017-07-28 15:21 UTC, andreychuk commented on docker-compose.yml
> +      - "5432:5432"
done

2017-07-28 15:21 UTC, andreychuk commented on docker-compose.yml
>      restart: always
done

2017-07-28 15:22 UTC, andreychuk commented on docker-compose.yml
> +    restart: always
done

2017-07-28 15:22 UTC, andreychuk commented on notify/Dockerfile
> +RUN chmod +x /root/run.sh
done

2017-07-28 15:23 UTC, andreychuk commented on notify/src/wait/wait-postgres.sh
> +#!/bin/sh
yep

2017-07-28 15:24 UTC, andreychuk commented on notify/src/supervisor/README.md
> +https://www.digitalocean.com/community/tutorials/how-to-install-and-manage-supervisor-on-ubuntu-and-debian-vps
nope, removed

2017-07-28 15:24 UTC, andreychuk commented on notify/src/wait/wfi/LICENSE
> +The MIT License (MIT)
moved to Dockerfile

2017-08-02 16:12 UTC, closed without merging